const products = [
  {
    id: 1,
    name: "Vans Siyah Kadın Sneaker",
    description: "Deri yüzey, kauçuk taban, kadın modeli.",
    img: "/images/image-1.png",
    price: 1599.0,
    amount: 1,
    category: "kadin",
  },
  {
    id: 2,
    name: "Reebok Erkek Sneaker",
    description:  "Süet dış yüzey, tekstil iç, erkek model.",
    img: "/images/image-2.png",
    price: 1900.0,
    amount: 1,
    category: "erkek",
  },
  {
    id: 3,
    name: "Nine West Kadın Topuklu Ayakkabı",
    description: "Deri topuklu kadın ayakkabı. Model: DUNNE 5PR.",
    img: "/images/image-3.png",
    price: 2499.0,
    amount: 1,
    category: "kadin",
  },
  {
    id: 4,
    name: "Lumberjack Siyah Kadın Outdoor",
    description: "VIBRA 4PR model, tekstil dış/astarlı spor ayakkabı.",
    img: "/images/image-4.png",
    price: 2500.0,
    amount: 1,
    category: "kadin",
  },
  {
    id: 5,
    name: "Kinetix Kız Çocuk Spor Ayakkabı",
    description: "RUBY PU B 5PR model, tekstil iç/dış, phylon taban.",
    img: "/images/image-5.png",
    price: 1800.0,
    amount: 1,
    category: "cocuk",
  },
  {
    id: 6,
    name: "Lumberjack Beyaz Erkek Sneaker",
    description: "POL PU 5PR model, suni deri dış, tekstil iç, phylon taban.",
    img: "/images/image-6.png",
    price: 2899.0,
    amount: 1,
    category: "erkek",
  },
  {
    id: 7,
    name: "Nike Bej Erkek Çocuk Sneaker",
    description: "COURT BOROUGH MID 2 modeli, deri/PU/tekstil dış, termo taban.",
    img: "/images/image-7.png",
    price: 1299.0,
    amount: 1,
    category: "cocuk",
  },
  {
    id: 8,
    name: "Nike Siyah Erkek Sneaker",
    description: "Giannis Immortality 4 modeli, suni deri dış, mesh iç, TPR taban.",
    img: "/images/image-8.png",
    price: 3000.0,
    amount: 1,
    category: "erkek",
  },
];

export default products;

